// Package docs is a placeholder regenerated by `make swag`.
// It exists so cmd/server/main.go can blank-import it during the first build,
// before swaggo has produced the real generated files.
package docs
