// Package main is the entry point of the Exnodes HRM API server.
//
// @title           Exnodes HRM API
// @version         0.1.0
// @description     HRM API for Exnodes — see /docs/superpowers/specs/2026-05-15-go-migration-design.md for the migration plan.
// @host            localhost:8080
// @BasePath        /
// @schemes         http
// @securityDefinitions.apikey BearerAuth
// @in              header
// @name            Authorization
package main

import (
	"fmt"
	"log"

	"github.com/gin-gonic/gin"

	"github.com/exnodes/hrm-api/internal/config"
	"github.com/exnodes/hrm-api/internal/handlers"
	"github.com/exnodes/hrm-api/internal/middleware"

	// Generated by `make swag` — imported for side effects (registers spec
	// with swaggo). The blank import line is updated after the first swag
	// run; until then the import is satisfied by the placeholder package
	// generated alongside the docs.
	_ "github.com/exnodes/hrm-api/docs/swagger"
)

func main() {
	cfg := config.Load()

	db, err := config.ConnectDB(cfg)
	if err != nil {
		log.Fatalf("database connect failed: %v", err)
	}

	if err := config.AssertMigrationsUpToDate(db, cfg.MigrationsDir); err != nil {
		log.Fatalf("migration check failed: %v", err)
	}

	gin.SetMode(cfg.GinMode)
	r := gin.New()

	// Middleware order matters: Recovery first (catches panics from later
	// middleware too), then logger, then CORS, then ErrorHandler (writes
	// the envelope at the end of the chain).
	r.Use(middleware.Recovery())
	r.Use(gin.Logger())
	r.Use(middleware.CORS())
	r.Use(middleware.ErrorHandler())

	handlers.RegisterRoutes(r, handlers.NewHandlers(), cfg.SwaggerEnabled)

	addr := fmt.Sprintf(":%s", cfg.Port)
	log.Printf("exnodes-hrm-api listening on %s (env=%s, swagger=%t)", addr, cfg.AppEnv, cfg.SwaggerEnabled)
	if err := r.Run(addr); err != nil {
		log.Fatalf("server failed: %v", err)
	}
}
