// Package main is the entry point of the Exnodes HRM API server.
//
// @title           Exnodes HRM API
// @version         0.1.0
// @description     HRM API for Exnodes — see /docs/superpowers/specs/2026-05-15-go-migration-design.md for the migration plan.
// @host            localhost:8080
// @BasePath        /
// @schemes         http
// @securityDefinitions.apikey BearerAuth
// @in              header
// @name            Authorization
package main

import (
	"context"
	"fmt"
	"log"
	"strings"
	"time"

	"github.com/gin-gonic/gin"

	"github.com/exnodes/hrm-api/internal/config"
	"github.com/exnodes/hrm-api/internal/handlers"
	"github.com/exnodes/hrm-api/internal/middleware"
	"github.com/exnodes/hrm-api/internal/permissions"
	"github.com/exnodes/hrm-api/internal/repositories"
	"github.com/exnodes/hrm-api/internal/services"

	// Generated by `make swag` — imported for side effects (registers spec
	// with swaggo). The blank import line is updated after the first swag
	// run; until then the import is satisfied by the placeholder package
	// generated alongside the docs.
	_ "github.com/exnodes/hrm-api/docs/swagger"
)

func main() {
	cfg := config.Load()

	db, err := config.ConnectDB(cfg)
	if err != nil {
		log.Fatalf("database connect failed: %v", err)
	}

	if err := config.AssertMigrationsUpToDate(db, cfg.MigrationsDir); err != nil {
		log.Fatalf("migration check failed: %v", err)
	}

	// ---- repositories ----
	userRepo := repositories.NewUserRepository(db)
	roleRepo := repositories.NewRoleRepository(db)
	employeeRepo := repositories.NewEmployeeRepository(db)
	dependentRepo := repositories.NewDependentRepository(db)
	tokenRepo := repositories.NewDeviceTokenRepository(db)
	quotaRepo := repositories.NewLeaveQuotaRepository(db)
	settingsRepo := repositories.NewNotificationSettingsRepository(db)
	departmentRepo := repositories.NewDepartmentRepository(db)
	positionRepo := repositories.NewPositionRepository(db)
	skillRepo := repositories.NewSkillRepository(db)
	employeeSkillRepo := repositories.NewEmployeeSkillRepository(db)
	labelRepo := repositories.NewLabelRepository(db)

	// ---- services ----
	authSvc := services.NewAuthService(userRepo, roleRepo, services.AuthConfig{
		JWTSecret:  cfg.JWTSecret,
		AccessTTL:  time.Duration(cfg.JWTAccessTTLMinutes) * time.Minute,
		RefreshTTL: time.Duration(cfg.JWTRefreshTTLDays) * 24 * time.Hour,
	})
	seedSvc := services.NewSeedService(db, userRepo, roleRepo, employeeRepo, services.SeedConfig{
		SuperAdminEmail:    cfg.SuperAdminEmail,
		SuperAdminPassword: cfg.SuperAdminPassword,
		SuperAdminName:     cfg.SuperAdminName,
	})

	uploadSvc, err := services.NewUploadService(context.Background(), cfg.Storage)
	if err != nil {
		log.Fatalf("upload service: %v", err)
	}
	empSvc := services.NewEmployeeService(db, employeeRepo, dependentRepo, userRepo, roleRepo, quotaRepo, uploadSvc)
	depSvc := services.NewDependentService(dependentRepo, employeeRepo)
	userSvc := services.NewUserService(userRepo, employeeRepo, tokenRepo, settingsRepo, empSvc)
	departmentSvc := services.NewDepartmentService(departmentRepo, positionRepo)
	positionSvc := services.NewPositionService(positionRepo, departmentRepo)
	skillSvc := services.NewSkillService(skillRepo, employeeSkillRepo, employeeRepo, uploadSvc)
	labelSvc := services.NewLabelService(labelRepo)

	// ---- run idempotent seed on boot ----
	if err := seedSvc.Seed(context.Background()); err != nil {
		log.Fatalf("seed: %v", err)
	}

	// ---- handlers ----
	authH := handlers.NewAuthHandler(authSvc)
	roleH := handlers.NewRoleHandler()
	empH := handlers.NewEmployeeHandler(empSvc)
	depH := handlers.NewDependentHandler(depSvc)
	userH := handlers.NewUserHandler(userSvc)
	departmentH := handlers.NewDepartmentHandler(departmentSvc)
	positionH := handlers.NewPositionHandler(positionSvc)
	skillH := handlers.NewSkillHandler(skillSvc)
	labelH := handlers.NewLabelHandler(labelSvc)

	// ---- CORS origin allow-list ----
	var corsOrigins []string
	for _, o := range strings.Split(cfg.CORSAllowedOrigins, ",") {
		if o = strings.TrimSpace(o); o != "" {
			corsOrigins = append(corsOrigins, o)
		}
	}
	if len(corsOrigins) == 0 && cfg.AppEnv == "production" {
		log.Fatal("config: CORS_ALLOWED_ORIGINS must be set in production")
	}

	gin.SetMode(cfg.GinMode)
	r := gin.New()

	// Middleware order matters: Recovery first (catches panics from later
	// middleware too), then logger, then CORS, then ErrorHandler (writes
	// the envelope at the end of the chain).
	r.Use(middleware.Recovery())
	r.Use(gin.Logger())
	r.Use(middleware.CORS(corsOrigins, cfg.AppEnv))
	r.Use(middleware.ErrorHandler())

	handlers.RegisterRoutes(r, handlers.NewHandlers(), cfg.SwaggerEnabled)

	// ---- routes ----
	v1 := r.Group("/api/v1")
	{
		// Public auth endpoints
		auth := v1.Group("/auth")
		auth.POST("/login", authH.Login)
		auth.POST("/refresh", authH.Refresh)

		// Protected endpoints
		authed := v1.Group("")
		authed.Use(middleware.JWT(userRepo, cfg.JWTSecret))

		authed.POST("/auth/logout", authH.Logout)
		authed.GET("/roles/permissions", roleH.ListPermissions)

		// ---- /users/me* self-service (auth only) ----
		authed.GET("/users/me", userH.GetMe)
		authed.POST("/users/me/change-password", userH.ChangeMyPassword)
		authed.POST("/users/me/change-email", userH.ChangeMyEmail)
		authed.POST("/users/me/device-tokens", userH.RegisterDeviceToken)
		authed.DELETE("/users/me/device-tokens/:token", userH.RemoveDeviceToken)
		authed.PATCH("/users/me/notification-settings", userH.UpdateMyNotificationSettings)

		// ---- /users/:id admin ----
		adminUsers := authed.Group("/users")
		adminUsers.GET("", middleware.RequirePerms(authSvc, permissions.PermUsersRead), userH.List)
		adminUsers.GET(":id", middleware.RequirePerms(authSvc, permissions.PermUsersRead), userH.Get)
		adminUsers.PATCH(":id", middleware.RequirePerms(authSvc, permissions.PermUsersUpdate), userH.AdminPatch)
		adminUsers.DELETE(":id", middleware.RequirePerms(authSvc, permissions.PermUsersDelete), userH.AdminDelete)
		adminUsers.PATCH(":id/change-password", middleware.RequirePerms(authSvc, permissions.PermUsersChangePwd), userH.AdminChangePassword)
		adminUsers.PUT(":id/roles", middleware.RequirePerms(authSvc, permissions.PermUsersManageRoles), userH.AssignRoles)

		// ---- /employees/me* self-service (auth only) ----
		authed.GET("/employees/me", empH.GetMe)
		authed.PATCH("/employees/me", empH.UpdateMe)
		authed.PATCH("/employees/me/avatar", empH.UpdateMyAvatar)

		// ---- /employees admin ----
		adminEmps := authed.Group("/employees")
		adminEmps.GET("", middleware.RequirePerms(authSvc, permissions.PermEmployeesRead), empH.List)
		adminEmps.POST("", middleware.RequirePerms(authSvc, permissions.PermEmployeesCreate), empH.Create)
		adminEmps.GET(":id", middleware.RequirePerms(authSvc, permissions.PermEmployeesRead), empH.Get)
		adminEmps.PATCH(":id", middleware.RequirePerms(authSvc, permissions.PermEmployeesUpdate), empH.Update)
		adminEmps.DELETE(":id", middleware.RequirePerms(authSvc, permissions.PermEmployeesDelete), empH.Delete)
		adminEmps.PATCH(":id/avatar", middleware.RequirePerms(authSvc, permissions.PermEmployeesUpdate), empH.UpdateAvatarAdmin)
		adminEmps.PATCH(":id/leave-quota", middleware.RequirePerms(authSvc, permissions.PermLeaveQuotaManage), empH.UpdateLeaveQuota)

		// ---- /employees/:id/dependents (owner or PermDependentsManage — enforced in handler) ----
		// NOTE: gin requires a single wildcard name per path position, so the
		// employee segment uses :id (shared with the admin /employees/:id tree)
		// and the nested dependent uses :dependentID.
		authed.GET("/employees/:id/dependents", depH.List)
		authed.POST("/employees/:id/dependents", depH.Create)
		authed.PATCH("/employees/:id/dependents/:dependentID", depH.Update)
		authed.DELETE("/employees/:id/dependents/:dependentID", depH.Delete)

		// ---- /departments ----
		departments := authed.Group("/departments")
		departments.GET("", middleware.RequirePerms(authSvc, permissions.PermDepartmentsRead), departmentH.List)
		departments.POST("", middleware.RequirePerms(authSvc, permissions.PermDepartmentsCreate), departmentH.Create)
		departments.GET(":id", middleware.RequirePerms(authSvc, permissions.PermDepartmentsRead), departmentH.Get)
		departments.PATCH(":id", middleware.RequirePerms(authSvc, permissions.PermDepartmentsUpdate), departmentH.Update)
		departments.DELETE(":id", middleware.RequirePerms(authSvc, permissions.PermDepartmentsDelete), departmentH.Delete)

		// ---- /positions ----
		positions := authed.Group("/positions")
		positions.GET("", middleware.RequirePerms(authSvc, permissions.PermPositionsRead), positionH.List)
		positions.POST("", middleware.RequirePerms(authSvc, permissions.PermPositionsCreate), positionH.Create)
		positions.GET(":id", middleware.RequirePerms(authSvc, permissions.PermPositionsRead), positionH.Get)
		positions.PATCH(":id", middleware.RequirePerms(authSvc, permissions.PermPositionsUpdate), positionH.Update)
		positions.DELETE(":id", middleware.RequirePerms(authSvc, permissions.PermPositionsDelete), positionH.Delete)

		// ---- /skills (catalog) ----
		skills := authed.Group("/skills")
		skills.GET("", middleware.RequirePerms(authSvc, permissions.PermSkillsRead), skillH.List)
		skills.POST("", middleware.RequirePerms(authSvc, permissions.PermSkillsCreate), skillH.Create)
		skills.GET(":id", middleware.RequirePerms(authSvc, permissions.PermSkillsRead), skillH.Get)
		skills.PATCH(":id", middleware.RequirePerms(authSvc, permissions.PermSkillsUpdate), skillH.Update)
		skills.DELETE(":id", middleware.RequirePerms(authSvc, permissions.PermSkillsDelete), skillH.Delete)

		// ---- /employees/:id/skills (assignment, nested) ----
		// Read uses PermEmployeesRead, write uses PermEmployeesUpdate — the
		// employee is the aggregate root for the skill list, so this matches
		// the existing employees-perms model.
		authed.GET("/employees/:id/skills", middleware.RequirePerms(authSvc, permissions.PermEmployeesRead), skillH.ListForEmployee)
		authed.PUT("/employees/:id/skills", middleware.RequirePerms(authSvc, permissions.PermEmployeesUpdate), skillH.ReplaceForEmployee)

		// ---- /announcement-labels (announcement label catalog) ----
		// Only two endpoints per REVISION NOTES item #4. Both gated by
		// PermAnnounceManage (the Admin + HR Manager roles received this
		// permission in seed_service.go as part of Phase 4).
		labels := authed.Group("/announcement-labels")
		labels.GET("", middleware.RequirePerms(authSvc, permissions.PermAnnounceManage), labelH.List)
		labels.POST("", middleware.RequirePerms(authSvc, permissions.PermAnnounceManage), labelH.GetOrCreate)
	}

	addr := fmt.Sprintf(":%s", cfg.Port)
	log.Printf("exnodes-hrm-api listening on %s (env=%s, swagger=%t)", addr, cfg.AppEnv, cfg.SwaggerEnabled)
	if err := r.Run(addr); err != nil {
		log.Fatalf("server failed: %v", err)
	}
}
